image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn package
    - cp ./advancedregionmarket/target/advancedregionmarket.jar ./advancedregionmarket.jar
  artifacts:
    expire_in: 1 week
    paths:
      - ./lib/*
      - ./advancedregionmarket.jar

test:
  stage: test
  script:
    - mvn test